# Generated by Django 4.0.5 on 2022-07-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_alter_entrada_contenido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='Articulos',
        ),
    ]
