# Generated by Django 4.0.5 on 2022-07-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0004_rename_entrada_articulos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Region',
        ),
    ]
